### PR TITLE
FMK-1038 : Enable /kernel/storage/dm/common test in kpet-db

### PR DESCRIPTION
**Pull request by idorax**
Currently, it fails when running the case via beaker, but it passes if we run it manually. The test maintainer is helping to figure out why, please hold on to review it until I remove WIP.

### CODE REVIEW

**Comment by jkrysl** [comment]
I think I finally fixed it, let's test it!
@cki-bot test

**Comment by rasibley** [comment]
hi @idorax can you test out @jkrysl changes ? @jkrysl fyi you can't trigger the bot for *new* tests, we just updated the description of the bot to make that more clear.

**Comment by jkrysl** [comment]
@rasibley Thanks for making it more clear, that's great! @idorax is on PTO till the end of this week, he should be back on Monday.

**Comment by idorax** [comment]
Thanks @jkrysl for fixing it, the test results on x86 look good now. Beaker jobs:
* RHEL8: 3777735
* RHEL7: 3777737
* Fedora30: 3777687

**Comment by idorax** [comment]
Please hold on review/merge this PR as [PR#373](https://github.com/CKI-project/tests-beaker/pull/373) is ongoing. That is, once PR#373 is done, I'll remove WIP for further review.

**Comment by idorax** [comment]
The code is synchronized with [PR#373](https://github.com/CKI-project/tests-beaker/pull/373), please help to review, thanks!

**Comment by idorax** [comment]
Hi @emanchado, would you please help to review this PR and get it merged? thanks!

**Comment by emanchado** [comment]
Sorry, I hadn't seen your earlier comment until now :sweat_smile:

**Comment by idorax** [comment]
Thank you, @emanchado! Is there any sample of  new-style metadata file? I'll follow it if file new PRs.

**Comment by emanchado** [comment]
@idorax: Unfortunately I'm not really familiar with it, myself 😢 While investigating something else, someone brought it to my attention. If I understand it correctly, the Makefiles are the old style, and the metadata files the new style.

There's an example here, but if it's also new to you, it would probably be better if you checked with someone who knows this better (and who can confirm that we should be doing this migration now), before doing any migration work:
https://github.com/CKI-project/tests-beaker/blob/master/misc/header-test/metadata

**Comment by idorax** [comment]
@emanchado, thanks for the sample and explanation. I'll check with @rasibley that we should follow metadata-file-style and get back to you.

**Pull request merged**
