### PR TITLE
Master dev3

### PR DESCRIPTION
**Pull request by lilinredhat**
[storage/hba] add FIO stress tests for HBA regression

### CODE REVIEW

**Comment by emanchado** [comment]
@lilinredhat: are you sure you created it from the current master? The same two conflicts are there... 😢

**Comment by lilinredhat** [comment]
synced master. close the PR and will open another PR.

**Comment by lilinredhat** [comment]
Opened another PR: https://github.com/CKI-project/tests-beaker/pull/425

**Comment by emanchado** [comment]
Hi! For the next time, could you force-push to the same branch? Sometimes it gets difficult to follow up, especially if something has been reviewed or approved, and then a new branch and/or PR are created...

Simply force-pushing (git push -f) to the same branch should update the PR.

**Pull request closed without merging**
