### PR TITLE
Update LTP and drop fixed test from "known issues"

### PR DESCRIPTION
**Pull request by emanchado**

### CODE REVIEW

**Comment by emanchado** [comment]
@cki-bot be a sweetheart and test!

**Comment by emanchado** [comment]
It seems to be fine. The failures are inconsistent, and the ones I looked at simply timed out after several hours (so, infra problem?).

**Comment by rasibley** [comment]
@emanchado, there was a watchdog time out due to setup phase taking too long, otherwise looks good!

**Comment by emanchado** [comment]
@rasibley: I updated the description of the Jira issue to replace the steps with a link to the new documentation. Not sure if we want to keep some of the steps, or a summary, or something.

**Pull request merged**
