### PR TITLE
fs/xfs/xfstests: do not report failure if subcase does not exist

### PR DESCRIPTION
**Pull request by jencce**
Remove 2 testcases that has been renamed upstream.

Signed-off-by: Murphy Zhou <xzhou@redhat.com>

### CODE REVIEW

**Comment by veruu** [comment]
If the testcases were just renamed, wouldn't it make more sense to add those into the list instead of just removing the old names?

**Comment by rasibley** [comment]
Thank you @jencce looks good, @veruu can you review ?

**Comment by veruu** [comment]
@rasibley I already left a question here in comments

**Comment by rasibley** [comment]
oops if I had looked ^^ I would have noticed, thanks @veruu !

**Comment by jencce** [comment]
shared/001 renamed to ext4/036
shared/003 renamed to ext4/037

Our listed cases are running for both xfs and ext4. These 2 cases only run on ext4, they are skipped when running on xfs. So I removed them.

**Comment by veruu** [comment]
Thanks for the explanation @jencce ! I'll add the info to the commit message if I'm able to do so while merging the change, please include things like this in there in the future so it's clear what happened

**Comment by jencce** [comment]
Thanks very much @veruu ! I should include more info in the commit message. Feel free to let me redo the commit if needed next time.

**Pull request merged**
