### PR TITLE
blktests: disable nvme/016 for RHEL7 s390x

### PR DESCRIPTION
**Pull request by yizhanglinux**
Signed-off-by: Yi Zhang <yi.zhang@redhat.com>

### CODE REVIEW

**Comment by yizhanglinux** [comment]
> Looks good, although it would be nice to know _why_ the test was disabled. Maybe add a note in the commit message?

Done

**Comment by emanchado** [comment]
Excellent, thanks! It's approved already, do you want me to merge or will you do it yourself?

**Comment by yizhanglinux** [comment]
> Excellent, thanks! It's approved already, do you want me to merge or will you do it yourself?

Could you help merge it, I have no idea how to do that.

Thanks
Yi

**Comment by emanchado** [comment]
Oops, it seems that `master` has changed since you created the PR, do you mind rebasing or merging `master` into your branch, to remove the warning before merging?

**Comment by yizhanglinux** [comment]
> Oops, it seems that `master` has changed since you created the PR, do you mind rebasing or merging `master` into your branch, to remove the warning before merging?

Rebase done, pls help merge it.

**Pull request merged**
