### PR TITLE
add scsi case check-scsi-vpd

### PR DESCRIPTION
**Pull request by guazhangRH**
add storage/scsi/check-scsi-vpd  for cki, please have a look if can be merged

### CODE REVIEW

**Comment by rasibley** [comment]
Thanks @guazhangRH I see some journal logging errors in the task output, can they be removed ?

**Comment by veruu** [comment]
Hi @guazhangRH ! I don't see any obvious issues in the code. Do you have a Beaker job with the new version so we can check if @rasibley 's comment is resolved?

**Comment by guazhangRH** [comment]
> Hi @guazhangRH ! I don't see any obvious issues in the code. Do you have a Beaker job with the new version so we can check if @rasibley 's comment is resolved?
Hi,  I have posted the beaker job link in the scsi case ticket which named "Enable scsi upstream tree and baseline testing" , you can found it in Jira, test passed on x86_64/ aarch64 platform, and don't see the errors which prompted by  @rasibley

**Comment by veruu** [comment]
@guazhangRH thanks! I didn't know about the JIRA ticket, just the email Rachel forwarded to me. I think we can merge the test now and in case any adjustments are needed you can always fill in another PR.

**Pull request merged**
