### PR TITLE
Update the test case because system hit panic when testing RHEL7

### PR DESCRIPTION
**Pull request by zhongchanghui**
Since rhel7's support for MD write-journal RAID is unstable, temporarily delete the journal raid part.
please take a look.

beaker job id: 6963820

### CODE REVIEW

**Comment by rasibley** [comment]
hi @zhongchanghui there are conflicts, I think your fork wasn't synced with master before you pushed your changes, can you please rebase ? Also does this fail only on rhel7 ? Why not instead add a condition to disable that part when running on rhel7, this way we don't have to disable the entire section.

**Comment by zhongchanghui** [comment]
Hello, Rachel, I have solved the conflict. The function of write-journal in mdadm is enabled on rhel7, but it is disabled in rhel8 now.I want to ensure the stability of md CKI case, so delete it temporarily. This part of the code, in the future can be added in the new case or the existing case to enable the write-journal function.

**Comment by zhongchanghui** [comment]
@rasibley

**Comment by rasibley** [comment]
Thank you @zhongchanghui  I hope we can re-enable that part after some time, I'm ok with the following changes, we can retest in kpet-db, @veruu is on PTO, but maybe @major can approve ?

**Pull request merged**
