### PR TITLE
audit-testsuite: on RHEL <8.1 skip filter_saddr_fam test

### PR DESCRIPTION
**Pull request by The-Mule**

### CODE REVIEW

**Comment by rasibley** [comment]
Thanks @The-Mule, looks like you also updated kernel-fips-mode test to remove the `/var/tmp/fips-disabled`file, was this intended ? If so, would you mind updating the commit message to make it more clear.

**Comment by The-Mule** [comment]
@rasibley, actually no. That was not intentional. I'll fix that.

**Comment by The-Mule** [comment]
Cleaned.

**Comment by rasibley** [comment]
Great thanks @The-Mule  ! LGTM !

**Pull request merged**
