### PR TITLE
Update to restraint rhtsRequires/requires part 1 of 3

### PR DESCRIPTION
**Pull request by ftjahjad**
update  httpd tests including libraries:
* Porting needed libraries that needed by httpd tests, and converting to fully restraints
* Updating httpd tests to fully restraint
* Use restraint metadata

### CODE REVIEW

**Comment by ftjahjad** [comment]
@cki-bot , please test

**Comment by rasibley** [comment]
Thanks Fendy, In the test results, looks like there were some errors during the setup phase for httpd mod_ssl, maybe they were there all along but didn't cause the job to fail, could be unrelated to these changes, can you double check ? 
```
:: [ 17:18:26 ] :: [   INFO   ] :: using '/var/tmp/beakerlib-108940808/backup-mod_ssl_smoke' as backup destination
:: [ 17:18:26 ] :: [  ERROR   ] :: rlFileBackup: File /etc/pki/tls/certs/localhost.crt does not exist.
:: [ 17:18:26 ] :: [   INFO   ] :: using '/var/tmp/beakerlib-108940808/backup-mod_ssl_smoke' as backup destination
:: [ 17:18:26 ] :: [  ERROR   ] :: rlFileBackup: File /etc/pki/tls/private/localhost.key does not exist.
:: [ 17:18:26 ] :: [   INFO   ] :: using '/var/tmp/beakerlib-108940808/backup-mod_ssl_smoke' as backup destination
:: [ 17:18:26 ] :: [  ERROR   ] :: rlFileBackup: File /var/log/httpd/error_log does not exist.
```

**Comment by rasibley** [comment]
Also looks like we disabled the php test in kpet-db so I would just pull the libraries out for this PR.

**Comment by ftjahjad** [comment]
@rasibley , 

:: [ 17:18:26 ] :: [   INFO   ] :: using '/var/tmp/beakerlib-108940808/backup-mod_ssl_smoke' as backup destination
:: [ 17:18:26 ] :: [  ERROR   ] :: rlFileBackup: File /etc/pki/tls/certs/localhost.crt does not exist.
.....
On my knowledge, that is just false warning(error): rlFileBackup tried to back up the certs and logs file before starting the test, but those files did not exist,
The test tried  to backup  those files and restored back at the end,


Just realized php-mysql is not in kpet-db.
going to remove un-needed libraries, and create another PR to delete php-mysql test.

**Comment by ftjahjad** [comment]
@cki-bot , please test again

**Pull request merged**
