### PR TITLE
FASTMOVING-415 Enable blktests in kpet-db

### PR DESCRIPTION
**Pull request by idorax**
To finish task FASTMOVING-415, we have to write block tests which focus on block and loop testing.

### CODE REVIEW

**Comment by rasibley** [comment]
hi @idorax did you have any passing test jobs ? When I tried to run it from your fork it failed with timeout: invalid option -- 't' ?
```

use_pty:FALSE /usr/share/restraint/plugins/run_task_plugins make run
git clone https://github.com/osandov/blktests.git
Cloning into 'blktests'...
cd blktests && make
make[1]: Entering directory '/mnt/tests/github.com/idorax/tests-beaker/archive/dev.0221.blktests.zip/storage/blk/blktests'
make -C src all
make[2]: Entering directory '/mnt/tests/github.com/idorax/tests-beaker/archive/dev.0221.blktests.zip/storage/blk/blktests/src'
cc  -O2 -Wall -Wshadow  -DHAVE_LINUX_BLKZONED_H -o loblksize loblksize.c
cc  -O2 -Wall -Wshadow  -DHAVE_LINUX_BLKZONED_H -o loop_get_status_null loop_get_status_null.c
cc  -O2 -Wall -Wshadow  -DHAVE_LINUX_BLKZONED_H -o openclose openclose.c
cc  -O2 -Wall -Wshadow  -DHAVE_LINUX_BLKZONED_H -o sg/dxfer-from-dev sg/dxfer-from-dev.c
cc  -O2 -Wall -Wshadow  -DHAVE_LINUX_BLKZONED_H -o sg/syzkaller1 sg/syzkaller1.c
cc  -O2 -Wall -Wshadow  -DHAVE_LINUX_BLKZONED_H -o nbdsetsize nbdsetsize.c
cc  -O2 -Wall -Wshadow  -DHAVE_LINUX_BLKZONED_H -o loop_change_fd loop_change_fd.c
cc  -O2 -Wall -Wshadow  -DHAVE_LINUX_BLKZONED_H -o zbdioctl zbdioctl.c
g++  -O2 -std=c++11 -Wall -Wextra -Wshadow -Wno-sign-compare -Werror  -DHAVE_LINUX_BLKZONED_H -o discontiguous-io discontiguous-io.cpp
make[2]: Leaving directory '/mnt/tests/github.com/idorax/tests-beaker/archive/dev.0221.blktests.zip/storage/blk/blktests/src'
make[1]: Leaving directory '/mnt/tests/github.com/idorax/tests-beaker/archive/dev.0221.blktests.zip/storage/blk/blktests'
cp runtest.sh runtest && chmod +x runtest
./runtest
Now run test case ./blktests/tests/block/001 ...
timeout: invalid option -- 't'
Try 'timeout --help' for more information.
** /kernel/storage/blk/blktests FAIL Score:1
Uploading resultoutputfile.log done
Now run test case ./blktests/tests/block/002 ...
timeout: invalid option -- 't'
Try 'timeout --help' for more information.
** /kernel/storage/blk/blktests FAIL Score:1
Uploading resultoutputfile.log done
.....
Now run test case ./blktests/tests/loop/007 ...
timeout: invalid option -- 't'
Try 'timeout --help' for more information.
** /kernel/storage/blk/blktests FAIL Score:1
Uploading resultoutputfile.log done
make: *** [Makefile:50: run] Error 33
```

**Comment by idorax** [comment]
Hi @rasibley, sorry it should be "timeout -t". Today I updated the runtest.sh by using blktests/check because it is the normal way to run the test cases, will paste a beaker job to FASTMOVING-415 once the test job is done.

**Comment by idorax** [comment]
Hi @rasibley, now the test results look good, please help to review again.
- RHEL8:  https://beaker.engineering.redhat.com/jobs/3369032
- RHEL7:  https://beaker.engineering.redhat.com/jobs/3369036

**Comment by rasibley** [comment]
@idorax thank you, I don't have further comments now, we can enable it and see how it runs in kpet-db CI, just a reminder don't include internal host names (beaker urls) in public comments :-) @veruu can you review as well ?

**Comment by idorax** [comment]
Thanks @rasibley, I'll keep in mind not to expose any internal url.

**Comment by veruu** [comment]
I don't see anything too weird in there, so let's try it out

**Pull request merged**
