### PR TITLE
Minor update for kvm-unit-tests to support aarch64

### PR DESCRIPTION
**Pull request by idorax**
Fix for FASTMOVING-484, check test can be run on aarch64 or not.

### CODE REVIEW

**Comment by veruu** [comment]
Thanks Vector! Do you think you can maybe merge the arch checking that's below this check together with the function? Since the function is already checking for x86_64 and aarch64 specific flags, any other arches should be unsupported and we don't need that additional arch check, right?

**Comment by idorax** [comment]
Thanks Veronica for your quick review and comments.  Let me remove L42-49 since the tests only support x86_64 and aarch64.

**Comment by idorax** [comment]
Veronica, removing L42-49 is done, please take a look again, thanks!

**Comment by veruu** [comment]
Thanks for a quick change! The test skipping message only mentions virt support on CPU and not the supported architectures, can they be added there so we don't lie in the logs please?

**Comment by idorax** [comment]
Veronica, I reorganized the code, and also did a basic unit testing, the test log is saved in [1]. Please review again, thanks!
[1] http://pastebin.test.redhat.com/702936

**Comment by veruu** [comment]
I haven't tested it myself but the changes look valid to me, thanks!

**Pull request merged**
