### PR TITLE
save and redirect perf test to log file,

### PR DESCRIPTION
**Pull request by ftjahjad**
somehow piping to external prg (ex: tee) could cause race condition based on observation/debugging

### CODE REVIEW

**Comment by ftjahjad** [comment]
@cki-bot , test please

**Comment by emanchado** [comment]
Don't be rude, @cki-bot, and do your test thing.

**Comment by emanchado** [comment]
The first link has two failures: the first is a WARN in a networking test (not really sure what that means), and the x86_64 failure seems infra-related ("External Watchdog Expired").

The second link also has some watchdog problem and another thing that kind of looks infra to me.

The third one also has timeouts and things like that, so probably also fine?

There are several failures with the networking tunnel test `vxlan basic`, but I doubt that's produced by your change?

I'll wait for confirmation from you or someone else before merging.

**Comment by ftjahjad** [comment]
@emanchado ,
it looks like the aborting/time-out not related with this PR change.
ran some (cloning) beakers tests and passed 
rhel7
x86_64:
https://beaker.engineering.redhat.com/recipes/7777273#task104570723
ppc64
https://beaker.engineering.redhat.com/recipes/7777272#task104570676

rhel8
x86_64:
https://beaker.engineering.redhat.com/recipes/7777290#task104571112
aarch64:
https://beaker.engineering.redhat.com/recipes/7777301#task104571218

**Pull request merged**
