### PR TITLE
ltp/include: backport fanotify0* patch

### PR DESCRIPTION
**Pull request by wangli5665**
Signed-off-by: Li Wang <liwang@redhat.com>

### CODE REVIEW

**Comment by wangli5665** [comment]
@cki-bot test

**Comment by wangli5665** [comment]
cki-bot test pass, please consider merge this commit.

**Comment by wangli5665** [comment]
@cki-bot test commit d925e24

**Comment by rasibley** [comment]
Results look good @veruu can we please merge ?

**Pull request merged**
