### PR TITLE
Stabilize audit-testsuite

### PR DESCRIPTION
**Pull request by ftjahjad**
Test-maintainer updates  test repo to stabilze  audit-testsuite.
Pull from test repo and open this PR to reflect code changes.

### CODE REVIEW

**Comment by rasibley** [comment]
@cki-bot can you please test ?

**Comment by spbnick** [comment]
@cki-bot, could you try to test this again?

**Comment by ftjahjad** [comment]
Hi @rasibley , @veruu 

please review the changes

**Comment by ftjahjad** [comment]
@cki-bot , pleas test again

**Comment by rasibley** [comment]
hi @ftjahjad  looks good to me, no failures related to audit that I can tell, @veruu can we please merge ?

**Pull request merged**
