### PR TITLE
Thinpsanity readme

### PR DESCRIPTION
**Pull request by ftjahjad**
LVM thinp sanity Readme.

### CODE REVIEW

**Comment by ftjahjad** [comment]
@spbnick 
could you review  this PR?

Thanks.

**Comment by spbnick** [comment]
Thank you, @ftjahjad, the changes look good, however could you please get rid of that merge commit, and squash all your commits into one, that just says "Add readme for thinp sanity"?

**Comment by veruu** [comment]
@spbnick if it helps, you can choose "squash and merge" instead of "rebase and merge" and pick a new commit message there too. Not useful if you want to have more commits but if you want to merge all the changes into one it's nice and removes the long waiting period because of timezones

**Comment by spbnick** [comment]
Thanks for the tip, @veruu! Never used that and it's useful.
I'd like Fendy to submit a bit more organized commits in the future, though, so review is easier. That's why I'm asking *him* :)

**Comment by veruu** [comment]
@spbnick sure, totally understood :)

**Comment by ftjahjad** [comment]
@spbnick 
all squashed in one commit on my understanding :-), my first trial on squashing.

**Comment by spbnick** [comment]
Looks great! Thank you, Fendy :smiley:!

**Pull request merged**
