### PR TITLE
Enable kvm self tests

### PR DESCRIPTION
**Pull request by idorax**
There is a case 'dirty_log_test' failing to be built, I just comment it out for the time being.

### CODE REVIEW

**Comment by rasibley** [comment]
Thank @idorax it runs well :-) can you please update the test to skip where it's not supported like this ? https://github.com/CKI-project/tests-beaker/blob/master/vm/kvm-unit-tests/runtest.sh#L54

**Comment by idorax** [comment]
Hi @rasibley, I have updated the related code according to your suggestion, please take a look again, thanks!

**Comment by rasibley** [comment]
Thanks @idorax can you please exit after skip without 'return 1' otherwise the test will skip/abort, we want result="Skip" status="Completed" for all scenarios, similar to https://github.com/CKI-project/tests-beaker/blob/master/vm/kvm-unit-tests/runtest.sh#L55

**Comment by idorax** [comment]
Hi @rasibley, the related code is updated, I use `exit 0` in rlSkip() explicitly.

**Comment by idorax** [comment]
Hi @rasibley, I updated the test code by patching `tools/include/linux/bitmap.h` so as to enable case 'dirty_log_test'. If it is fixed in the future, we'll remove the patch accordingly. Please review again, thanks!

**Comment by rasibley** [comment]
Thanks @idorax looks good now! I see it passes/skipped correctly now, I'll leave it to @veruu to review/merge.

**Pull request merged**
