### PR TITLE
ltp/knownissue: enable hugetlb test in CKI-ltp

### PR DESCRIPTION
**Pull request by wangli5665**
This shortage memory issue has been solved by:
  commit afe63f3500c1 (ltp: setup nr_hpage for hugetlb if MemAvailable is low)

So let's move hugetlb tests out of the blacklist.

Signed-off-by: Li Wang <liwang@redhat.com>

### CODE REVIEW

**Comment by wangli5665** [comment]
Hi, I just noticed that CKI-ltp has disabled the hugetlb part for a quite long time, the beaker job submit a blank log to mark this part pass(that makes me thought it works well). 
Anyway, I have submitted a fix for the TBROK problem in pull request#499, so here let's enable it.

**Comment by rasibley** [comment]
Thanks @wangli5665 ! cc @idorax

**Comment by rasibley** [comment]
@cki-bot please test

**Comment by rasibley** [comment]
@emanchado fyi looks like the bot didn't trigger the first time, maybe because you added it as part of the review vs a comment ?

**Comment by rasibley** [comment]
FYI see test results here: J:4187146

**Comment by wangli5665** [comment]
Thanks for testing this, from these test result, LTP/hugetlb only get one failure. But it seems not involves by this patchset, it's more like system or LTP itself issue. 

     2	tag=hugeshmctl01 stime=1586439959
     3	cmdline="hugeshmctl01 -i 5"
     4	contacts=""
     5	analysis=exit
     6	<<<test_output>>>
     7	tst_test.c:1227: INFO: Timeout per run is 0h 05m 00s
     8	mem.c:817: INFO: set nr_hugepages to 128
     9	hugeshmctl01.c:197: PASS: pid, size, # of attaches and mode are correct - pass #0
    10	hugeshmctl01.c:197: PASS: pid, size, # of attaches and mode are correct - pass #1
    11	hugeshmctl01.c:263: PASS: new mode and change time are correct
    12	hugeshmctl01.c:279: PASS: shmctl in func_rmid() failed as expected, shared memory appears to be removed
    13	tst_checkpoint.c:147: BROK: hugeshmctl01.c:152: tst_checkpoint_wait(0, 10000): ETIMEDOUT (110)
    14	mem.c:817: INFO: set nr_hugepages to 0
    15	
    16	Summary:
    17	passed   4
    18	failed   0
    19	skipped  0
    20	warnings 0

**Comment by rasibley** [comment]
Thanks @wangli5665 it seems to fail pretty consistently across systems, should we add it to the known issues ?

**Comment by wangli5665** [comment]
The futex(0x7f0b36c48014, FUTEX_WAIT, 0, {tv_sec=10, tv_nsec=0} syscall was kill by signal SIGSEGV, I'm not sure why the test does not work with only more than 2 iterations. It looks like a bug exist in 5.5.15-rc1-cd17199.cki. Btw, I get PASS in kernel-5.6 by manual.

[pid 796426] futex(0x7f0b36c48014, FUTEX_WAIT, 0, {tv_sec=10, tv_nsec=0} <unfinished ...>
[pid 796435] <... set_robust_list resumed>) = 0 <0.000036>
[pid 796435] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7f0b2ea00000} ---
[pid 796435] +++ killed by SIGSEGV (core dumped) +++
[pid 796426] <... futex resumed>)       = ? ERESTART_RESTARTBLOCK (Interrupted by signal) <0.657410>
[pid 796426] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_DUMPED, si_pid=796435, si_uid=0, si_status=SIGSEGV, si_utime=0, si_stime=0} ---
[pid 796426] restart_syscall(<... resuming interrupted futex ...>) = -1 ETIMEDOUT (Connection timed out) <9.342804>
[pid 796426] write(2, "tst_checkpoint.c:147: \33[1;31mBRO"..., 106tst_checkpoint.c:147: BROK: hugeshmctl01.c:152: tst_checkpoint_wait(0, 10000): ETIMEDOUT (110)
) = 106 <0.000057>

**Comment by rasibley** [comment]
Thanks @wangli5665, the master branch has a recent commit as of yesterday, updating your branch and re-testing.

**Comment by rasibley** [comment]
New test job: 4189392

**Comment by rasibley** [comment]
Test job looks good now, excluding the two jobs which didn't kickstart, thanks again @wangli5665  !

**Pull request merged**
