### PR TITLE
xfstests: cleanup

### PR DESCRIPTION
**Pull request by jencce**
Clean up for running on Fedora.

### CODE REVIEW

**Comment by veruu** [comment]
@spbnick @rasibley do you want to check this pull out? The changes look good to me but I'm absolutely not familiar with the test so asking for a bonus set of eyes :)

**Comment by rasibley** [comment]
@jencce I noticed you were removing a lot of rhel specific code, this version of the test currently runs on rhel7, rhel8, and Fedora, just wanted to confirm that any changes you made will not prevent it from running on all releases (including RHEL) ?

**Comment by jencce** [comment]
@rasibley  Sure. It will not break running on RHEL and Fedora. I have it tested. The removal is for running smoothly on Fedora without breaking running on RHEL.

**Comment by rasibley** [comment]
@jencce thanks for confirming! @veruu I reviewed and don't see any reason we can't merge this, although I'm not an expert of xfstests, but it looks reasonable to me :-)

**Comment by veruu** [comment]
Thanks for checking! Merging!

**Pull request merged**
