### PR TITLE
Rename template/dummy-test to example

### PR DESCRIPTION
**Pull request by spbnick**
Rename a somewhat obscurely-named "template/dummy-test" to "example" to
increase its visibility and inspire its further development.

### CODE REVIEW

**Comment by spbnick** [comment]
@rasibley, could you take a look at this?

**Comment by rasibley** [comment]
If running in beaker, at a minimum, the test still needs to source either the rhts or beakerlib environment to be able to communicate back to the harness, best practice is to just use beakerlib:
```
# Include Beaker environment
. /usr/bin/rhts-environment.sh || exit 1
. /usr/share/beakerlib/beakerlib.sh || exit 1
```

However if the purpose is to write a dummy test without the beaker restriction, then looks good to me.

**Comment by veruu** [comment]
@spbnick is this still relevant? Will someone work on the PR or should we close it?

**Comment by spbnick** [comment]
Yeah, would be good to have a more realistic test, even if requiring Beaker. For now though, I'm just increasing its visibility by renaming the existing test.

**Pull request merged**
