### PR TITLE
port tunnel gre basic test

### PR DESCRIPTION
**Pull request by ftjahjad**
Port networking tunnel GRE basic  to CKI test-beaker.

### CODE REVIEW

**Comment by ftjahjad** [comment]
@rasibley  and @veruu 

Please review gre basic test pull request.

**Comment by rasibley** [comment]
Thanks @ftjahjad, I'm good with the changes

**Comment by veruu** [comment]
@ftjahjad I see the log couldn't be created on the RHEL8 job:

```[ WARNING  ] :: cannot create journal.xml due to missing python interpreter```

Can you take a look at that? The log was created fine on the other jobs.
Besides this issue the code looks good! :+1:

**Comment by rasibley** [comment]
@veruu fyi https://bugzilla.redhat.com/show_bug.cgi?id=1637625  You'll actually see it in all the logs where beakerlib is used for rhel8.

**Comment by veruu** [comment]
@rasibley thanks, I wasn't aware of that bug. In that case (since the job itself passes) we can merge

**Pull request merged**
