### PR TITLE
FASTMOVING-1442: Fix ppc64le podman test errors

### PR DESCRIPTION
**Pull request by major**
* Use the new bats package from Fedora 31
* Add a multi-arch wrapper for non-x86_64 systems
* Ensure 110-history test uses default container image
* Switch to prettier bats output option
* Add emojis, because why not? 🥰

[test beaker]

Signed-off-by: Major Hayden <major@redhat.com>

### CODE REVIEW

**Comment by major** [comment]
@cki-bot test

**Comment by major** [comment]
Good point. Let's see how this tests elsewhere and then I'll go back and run a manual test.

**Comment by major** [comment]
@rasibley I started `J:3904704` to test it manually.

**Comment by major** [comment]
@rasibley The RHEL 8 manual test and test through Beaker passed. I'll remove that `-p` option from bats and rebase.

**Comment by rasibley** [comment]
Thanks @major LGTM

**Pull request merged**
