### PR TITLE
add new test /kernel/misc/header-test

### PR DESCRIPTION
**Pull request by jbastian**
This test should run if any header files (*.h) are added or modified.

### CODE REVIEW

**Comment by ftjahjad** [comment]
@rasibley , and @veruu 

please review @jbastian  header-test PR.

**Comment by rasibley** [comment]
@ftjahjad from my limited understanding of the test, I don't see any issues with merging, I see it passed on all trees tested by @jbastian and again using your jobs in the brew pipeline for rhel8. I don't believe this test is supported on ARK/Fedora kernels based on Jeff's testing and no corresponding dir for the upstream kernel, but we can let @jbastian confirm. Please test in brew pipeline for rhel7 arches since don't have kpet-db CI for brew, and exclude from upstream/ark trees when you file the MR to kpet-db.

**Comment by jbastian** [comment]
Currently it does not support Fedora or ARK since it looks for dist-tags like "el6" or "el7", but it should be fairly easy to add support for Fedora or generic upstream kernels.

**Comment by rasibley** [comment]
Thanks @jbastian ! With Jeff's latest changes it's passing everywhere, @veruu please considering merging :-) test jobs in the ticket.

**Pull request merged**
