### PR TITLE
Adapted to cthon04 upstream modification

### PR DESCRIPTION
**Pull request by tcler**
upstream has solved the problem of compile failure
the patches related to tests.init are no longer needed

Signed-off-by: Jianhong Yin <jiyin@redhat.com>

### CODE REVIEW

**Comment by tcler** [comment]
test

**Comment by rasibley** [comment]
@cki-bot test please

**Comment by veruu** [comment]
There was an unrelated problem with the pipeline which should hopefully be resolved now. @cki-bot can you test it out again?

**Comment by tcler** [comment]
@cki-bot test again please

**Comment by rasibley** [comment]
@veruu can we please merge this ? I'm not seeing any connectathon failures

**Comment by veruu** [comment]
@rasibley connectathon didn't run in any pipelines from the last report :( do you have a separate job?

**Comment by rasibley** [comment]
@veruu it's only enabled for rhel8, but you should see it ran and passed in the rhel8 pipeline :-)

**Comment by veruu** [comment]
@rasibley ah ok! Thanks for explanation, I forgot it shouldn't run everywhere and got confused.

Merging!

**Pull request merged**
