### PR TITLE
initial commit of socket_fuzz test

### PR DESCRIPTION
**Pull request by rasibley**
Hi @veruu please review, test jobs in the ticket.

### CODE REVIEW

**Comment by rasibley** [comment]
hi @liuhangbin does this test always pass or is the main point to detect a panic in the kernel, it's not very clear in the Purpose file. Thanks!

**Comment by liuhangbin** [comment]
Yes, this test is just to fuzz socket functions and make sure no kernel panic.

**Comment by rasibley** [comment]
hi @veruu I updated the purpose file is it ok to merge now ?

**Comment by veruu** [comment]
Thanks for the updated info!

**Pull request merged**
