### PR TITLE
initial commit of vxlan basic test

### PR DESCRIPTION
**Pull request by rasibley**
@veruu please review :-)

### CODE REVIEW

**Comment by rasibley** [comment]
hi @veruu this isn't a multi-host test, we currently run this on single hosts now, just porting so we can run on upstream kernels. If we were to enable multi-host we would need to confirm the hosts were available to us or send over the UMB.

**Comment by veruu** [comment]
@rasibley hm, ok. The test says `--topo=multihost` and deals with client/server configuration so it's confusing. Can you mention it can run on a single host in the test please to make it clear?

**Comment by rasibley** [comment]
@veruu well there is two ways to runs it, singlehost or multihost:
 attr: {level: Tier1, type: singlehost, distronotin: RHEL-6}

Would it be ok if we left it in case we can run on a multi-host environment over umb in the future ? Otherwise I can remove it.

**Comment by veruu** [comment]
@rasibley sure, we can keep the functionality for future cases and just putting "can run standalone or multihost" into the readme file would be enough

**Pull request merged**
