### PR TITLE
[pull request] xfstests: move to proper location

### PR DESCRIPTION
**Pull request by jencce**
Some minor fixes.

### CODE REVIEW

**Comment by spbnick** [comment]
This looks good overall. Thank you, Xiong.

I have one question about the "xfstests: remove some RHEL unsupported testcases": is this only concerning RHEL? Would those normally work on e.g. Fedora? I.e. could they be useful for upstream kernel testing?

**Comment by jencce** [comment]
Very good point @spbnick !
I tested on RHEL-7/8 for xfs and ext4, which is 4 setups. And I removed testcases that is "not run" in at least 3 out of these 4 setups.
You are right. They may be useful for Fedora or upstream kernel. We'd better keep them. I can revert that commit before you merge this PR.

**Comment by spbnick** [comment]
Let's leave them on, if testing on RHEL7/8 won't break. Thank you, @jencce!

**Comment by jencce** [comment]
I've done the revert.This PR can be merged if no more fix needed. Thanks!

**Comment by spbnick** [comment]
Thank you, @jencce! This should be good to go. However, could you please simply remove the two last commits from this PR (which remove and then add tests), so there's less noise in the Git history? Thank you.

**Comment by jencce** [comment]
Sure, done. Thanks for reviewing!

**Comment by spbnick** [comment]
Thank you, @jencce, merged!

**Pull request merged**
