### PR TITLE
audit-testsuite: pin to known-good upstream commit

### PR DESCRIPTION
**Pull request by WOnder93**
Latest master has some new tests that are failing on RHEL-7. Pin to a
last upstream commit that works until the test is adapted. This will
also prevent new false failures from appearing when upstream repo is
updated with more tests.

Cc: @The-Mule

### CODE REVIEW

**Comment by rasibley** [comment]
Thank you, LGTM!

**Comment by The-Mule** [comment]
Rachel, could you please keep this one open for one more day. I had a slightly extended approach and I think it can be incorporated to what Ondrej proposed. I will look into that today and let you know by the end of the day (CET).

**Comment by rasibley** [comment]
Hi @The-Mule , sure I'll leave it open, let me know once it's ready to be merged.

**Comment by The-Mule** [comment]
OK, I have different fix in the end - excluded bpf and time_change tests on RHEL-7 and running all tests from master on RHEL-8.1 (excluded saddr_fam on RHEL-8.0 already before). 

I guess the easiest would be to open a new PR. We can close this one without merging. I am really sorry for all troubles.  

New PR can be found here - https://github.com/CKI-project/tests-beaker/pull/492. This one is obsoleted by it.

**Comment by WOnder93** [comment]
OK, closing in favor of #492. Thanks, @The-Mule!

**Pull request closed without merging**
