### PR TITLE
Audit testsuite rhel7 fix

### PR DESCRIPTION
**Pull request by The-Mule**
New tests were added recently to audit-testsuite (kernel audit upstream testsuite for audit used by this beaker tests). Two of them are not RHEL-7 compatible and need to be filtered out, they run correctly on RHEL-8.

### CODE REVIEW

**Comment by WOnder93** [comment]
I'd still suggest pinning to the current latest commit (ece04ca5517449930cafdddd8c076a258d0e0faf) so that when a new test is added upstream we don't immediately start getting a flood of CKI failures. We would then only bump the commit manually along with all needed sauce once we verify that the result works well across distros.

**Comment by The-Mule** [comment]
Yeah, I forgot to take that approach (using the latest "stable" instead of master) from you last PR! :) Sorry about that. Let me fix that.

**Comment by The-Mule** [comment]
Sure, sorry for that, it should be fixed now and it is ready to be merged. Thanks!

**Comment by emanchado** [comment]
Excellent, thanks for the quick fix!

**Pull request merged**
