### PR TITLE
[storage/hba]  add FIO stress tests for HBA regression

### PR DESCRIPTION
**Pull request by lilinredhat**
Signed-off-by: lilin <lilin@redhat.com>

### CODE REVIEW

**Comment by emanchado** [comment]
Oops, can you please resolve the conflicts first?

**Comment by emanchado** [comment]
Hm, it seems that this test is already in the repo?? https://github.com/CKI-project/tests-beaker/tree/master/storage/hba/san-device-stress

**Comment by lilinredhat** [comment]
Hello, 
Yes. This test is already in the repo. Some commands in main.sh are wrong. I changed main.sh. How should I do to update it? 
Thanks! 

----- 原始邮件 -----

发件人: "Esteban Manchado Velázquez" <notifications@github.com> 
收件人: "CKI-project/tests-beaker" <tests-beaker@noreply.github.com> 
抄送: "lilinredhat" <lilin@redhat.com>, "Author" <author@noreply.github.com> 
发送时间: 星期五, 2019年 9 月 27日 下午 6:35:17 
主题: Re: [CKI-project/tests-beaker] [storage/hba] add FIO stress tests for HBA regression (#382) 



Hm, it seems that this test is already in the repo?? https://github.com/CKI-project/tests-beaker/tree/master/storage/hba/san-device-stress

**Comment by emanchado** [comment]
I think the best is probably to:
1. Keep a copy of the whole folder, as it appears in this branch,
1. Delete this branch, and
1. Create a new branch (+ PR) from current `master`, but overwriting the whole `storage/hba/san-device-stress` folder with what you saved in the first step.

Does that make sense?

**Comment by rasibley** [comment]
Hi @lilinredhat have you had a chance to work on this PR, there is no activity for over 3 weeks now, if you need help adjusting the PR, we can help, thanks!

**Comment by lilinredhat** [comment]
Hi @rasibley ,
I deleted this branch and created a new branch (+ PR) from current master:
https://github.com/CKI-project/tests-beaker/pull/423
What should I do next step?

**Comment by lilinredhat** [comment]
synced master. close the PR and will open another PR.

**Pull request closed without merging**
